from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(Person)
admin.site.register(Work_day)
admin.site.register(Classroom)
admin.site.register(Classroom_day)
admin.site.register(Classroom_place)
admin.site.register(Appointment)
admin.site.register(Enrolment_teacher)
admin.site.register(Enrolment_student)
admin.site.register(Person_request)
admin.site.register(Classroom_request)
admin.site.register(Classroom_day_request)
admin.site.register(Enrolment_teacher_request)
admin.site.register(Enrolment_student_request)
admin.site.register(Work_day_request)
admin.site.register(Person_record)
admin.site.register(Work_day_record)
admin.site.register(Appointment_record)
admin.site.register(Classroom_record)
admin.site.register(Classroom_day_record)
admin.site.register(Enrolment_teacher_record)
admin.site.register(Enrolment_student_record)
admin.site.register(Notification)